repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: check-json
  - id: check-yaml
- repo: https://github.com/DavidAnson/markdownlint-cli2
  rev: v0.2.0
  hooks:
  - id: markdownlint-cli2
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.28.1
  hooks:
  - id: markdownlint
