repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: check-json
  - id: check-yaml
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.24.0
  hooks:
  - id: markdownlint
