repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: check-json
  - id: check-yaml
- repo: https://github.com/DavidAnson/markdownlint-cli2
  rev: next
  hooks:
  - id: markdownlint-cli2
  - id: markdownlint-cli2-fix
  - id: markdownlint-cli2-config
    args: [configuration/.markdownlint-cli2.jsonc]
  - id: markdownlint-cli2-docker
  - id: markdownlint-cli2-fix-docker
  - id: markdownlint-cli2-config-docker
    args: [configuration/.markdownlint-cli2.jsonc]
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: master
  hooks:
  - id: markdownlint
  - id: markdownlint-fix
  - id: markdownlint-docker
  - id: markdownlint-fix-docker
