repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: check-json
  - id: check-yaml
- repo: https://github.com/DavidAnson/markdownlint-cli2
  rev: v0.0.13
  hooks:
  - id: markdownlint-cli2
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: 014e777db9691db091c5b1de9b459a8c27609058
  hooks:
  - id: markdownlint
