name: Check links in Markdown files (linkinator)

on:
  pull_request:
  push:
  schedule:
    - cron: '30 12 * * *'
  workflow_dispatch:

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          repository: DavidAnson/markdownlint
      - name: Run linkinator
        uses: JustinBeckwith/linkinator-action@v1
        with:
          paths: "**/*.md"
          directoryListing: true
          markdown: true
          linksToSkip: "node_modules/, test/, ^https://github.com/.*/search\\?q="
  markdownlint-cli2:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          repository: DavidAnson/markdownlint-cli2
      - name: Run linkinator
        uses: JustinBeckwith/linkinator-action@v1
        with:
          paths: "**/*.md"
          directoryListing: true
          markdown: true
          linksToSkip: "node_modules/, test/"
  vscode-markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          repository: DavidAnson/vscode-markdownlint
      - name: Run linkinator
        uses: JustinBeckwith/linkinator-action@v1
        with:
          paths: "**/*.md"
          directoryListing: true
          markdown: true
          linksToSkip: "node_modules/"
