name: Check links in Markdown files

on:
  pull_request:
  push:
  schedule:
    - cron: '30 12 * * *'
  workflow_dispatch:

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          repository: DavidAnson/markdownlint
      - name: Install markdown-link-check
        run: npm install markdown-link-check --no-package-lock
      - name: Create config file
        run: printf '{ "ignorePatterns"\: [ { "pattern"\: "/search\?q=" } ] }' \> config.json
      - name: Run markdown-link-check
        run: find . -name '*.md' -not -path './node_modules/*' -not -path './test/*' -print0 | xargs -0 -n 1 ./node_modules/.bin/markdown-link-check --verbose --config config.json
  markdownlint-cli2:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          repository: DavidAnson/markdownlint-cli2
      - name: Install markdown-link-check
        run: npm install markdown-link-check --no-package-lock
      - name: Run markdown-link-check
        run: find . -name '*.md' -not -path './node_modules/*' -not -path './test/*' -print0 | xargs -0 -n 1 ./node_modules/.bin/markdown-link-check -v
  vscode-markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          repository: DavidAnson/vscode-markdownlint
      - name: Install markdown-link-check
        run: npm install markdown-link-check --no-package-lock
      - name: Run markdown-link-check
        run: find . -name '*.md' -not -path './node_modules/*' -not -path './test/*' -print0 | xargs -0 -n 1 ./node_modules/.bin/markdown-link-check -v
