name: Smoke lint real-world repositories

on:
  pull_request:
  push:
  schedule:
    - cron: '30 12 * * *'
  workflow_dispatch:

jobs:
  dotnet-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          repository: dotnet/docs
      - name: Install markdownlint CLIs
        run: npm install markdownlint-cli markdownlint-cli2 --no-package-lock --production
      - name: Run markdownlint-cli
        run: ./node_modules/.bin/markdownlint '**/*.md' --ignore 'samples/**/*.md' --ignore node_modules
      - name: Run markdownlint-cli2
        run: ./node_modules/.bin/markdownlint-cli2 '**/*.md' '#samples/**/*.md' '#node_modules'
      - uses: DavidAnson/markdownlint-cli2-action@v5
        with:
          globs: |
            **/*.md
            !samples/**/*.md
            !node_modules
  eslint-eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          repository: eslint/eslint
      - name: Install markdownlint CLIs
        run: npm install markdownlint-cli markdownlint-cli2 --no-package-lock
      - name: Run markdownlint-cli
        run: ./node_modules/.bin/markdownlint 'docs/**/*.md' --ignore node_modules
      - name: Run markdownlint-cli2
        run: ./node_modules/.bin/markdownlint-cli2 'docs/**/*.md' '#node_modules'
      - uses: DavidAnson/markdownlint-cli2-action@v5
        with:
          globs: |
            docs/**/*.md
            !node_modules
  mkdocs-mkdocs:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          repository: mkdocs/mkdocs
      - name: Install markdownlint CLIs
        run: npm install markdownlint-cli markdownlint-cli2 --no-package-lock --production
      - name: Run markdownlint-cli
        run: ./node_modules/.bin/markdownlint README.md CONTRIBUTING.md 'docs/*' --ignore docs/CNAME --ignore node_modules
      - name: Clone configuration file
        run: cp .markdownlintrc .markdownlint.jsonc
      - name: Run markdownlint-cli2
        run: ./node_modules/.bin/markdownlint-cli2 README.md CONTRIBUTING.md 'docs/*' '#docs/CNAME' '#node_modules'
      - uses: DavidAnson/markdownlint-cli2-action@v5
        with:
          globs: |
            README.md
            CONTRIBUTING.md
            docs/*
            !docs/CNAME
            !node_modules
  mochajs-mocha:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          repository: mochajs/mocha
      - name: Install markdownlint CLIs
        run: npm install markdownlint-cli markdownlint-cli2 --no-package-lock
      - name: Run markdownlint-cli
        run: ./node_modules/.bin/markdownlint '*.md' 'docs/**/*.md' '.github/*.md' 'lib/**/*.md' 'test/**/*.md' 'example/**/*.md' --ignore node_modules
      - name: Run markdownlint-cli2
        run: ./node_modules/.bin/markdownlint-cli2 '*.md' 'docs/**/*.md' '.github/*.md' 'lib/**/*.md' 'test/**/*.md' 'example/**/*.md' '#node_modules'
      - uses: DavidAnson/markdownlint-cli2-action@v5
        with:
          globs: |
            *.md
            docs/**/*.md
            .github/*.md
            lib/**/*.md
            test/**/*.md
            example/**/*.md
            !node_modules
  pi-hole-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          repository: pi-hole/docs
      - name: Install markdownlint CLIs
        run: npm install markdownlint-cli markdownlint-cli2 --no-package-lock
      - name: Run markdownlint-cli
        run: ./node_modules/.bin/markdownlint '**/*.md' --ignore node_modules
      - name: Run markdownlint-cli2
        run: ./node_modules/.bin/markdownlint-cli2 '**/*.md' '#node_modules'
      - uses: DavidAnson/markdownlint-cli2-action@v5
        with:
          globs: |
            **/*.md
            !node_modules
  webhintio-hint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          repository: webhintio/hint
      - name: Install markdownlint CLIs
        run: npm install markdownlint-cli markdownlint-cli2 --no-package-lock
      - name: Run markdownlint-cli
        run: ./node_modules/.bin/markdownlint '**/*.md' --ignore '**/CHANGELOG.md' --ignore node_modules
      - name: Clone configuration file
        run: cp .markdownlintrc .markdownlint.jsonc
      - name: Run markdownlint-cli2
        run: ./node_modules/.bin/markdownlint-cli2 '**/*.md' --ignore '**/CHANGELOG.md' '#node_modules'
      - uses: DavidAnson/markdownlint-cli2-action@v5
        with:
          globs: |
            **/*.md
            !**/CHANGELOG.md
            !node_modules
  webpack-webpack-js-org:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          repository: webpack/webpack.js.org
      - name: Install markdownlint CLIs
        run: npm install markdownlint-cli markdownlint-cli2 --no-package-lock
      - name: Run markdownlint-cli
        run: ./node_modules/.bin/markdownlint '**/*.md' --ignore node_modules
      - name: Run markdownlint-cli2
        run: ./node_modules/.bin/markdownlint-cli2 '**/*.md' '#node_modules'
      - uses: DavidAnson/markdownlint-cli2-action@v5
        with:
          globs: |
            **/*.md
            !node_modules
  v8-v8-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          repository: v8/v8.dev
      - name: Install markdownlint CLIs
        run: npm install markdownlint-cli markdownlint-cli2 --no-package-lock
      - name: Run markdownlint-cli
        run: ./node_modules/.bin/markdownlint 'src/**/*.md' --ignore node_modules
      - name: Run markdownlint-cli2
        run: ./node_modules/.bin/markdownlint-cli2 'src/**/*.md' '#node_modules'
      - uses: DavidAnson/markdownlint-cli2-action@v5
        with:
          globs: |
            src/**/*.md
            !node_modules
