name: Smoke test packages and container images

on:
  pull_request:
  push:
  schedule:
    - cron: '30 12 * * *'
  workflow_dispatch:

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
      - name: Install Dependencies
        run: cd markdownlint && npm install --no-package-lock --production
      - name: Run Tests
        run: cd markdownlint && npm run test
  markdownlint-cli2:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
      - name: Install Dependencies
        run: cd markdownlint-cli2 && npm install --no-package-lock --production
      - name: Run Tests
        run: cd markdownlint-cli2 && npm run test
  markdownlint-cli2-global:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
      - name: Install Dependencies
        run: cd markdownlint-cli2 && sudo npm install --global --no-package-lock --production markdownlint-cli2 markdownlint-cli2-formatter-json markdownlint-cli2-formatter-junit markdownlint-cli2-formatter-pretty markdownlint-cli2-formatter-summarize
      - name: Run Tests
        run: cd markdownlint-cli2 && npm run test
  markdownlint-cli-container:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/igorshubovych/markdownlint-cli:latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Lint
        run: markdownlint README.md
      - name: Lint and fix
        run: markdownlint --fix README.md
  markdownlint-cli2-container:
    runs-on: ubuntu-latest
    container:
      image: davidanson/markdownlint-cli2:0.4.0
      options: -u root
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Lint
        run: markdownlint-cli2 README.md
      - name: Lint and fix
        run: markdownlint-cli2-fix README.md
      - name: Lint with config
        run: markdownlint-cli2-config configuration/.markdownlint-cli2.jsonc README.md
  markdownlint-cli-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Lint via Docker
        run: docker run -v $PWD:/workdir ghcr.io/igorshubovych/markdownlint-cli:latest README.md
  markdownlint-cli2-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Lint via Docker
        run: docker run -v $PWD:/workdir davidanson/markdownlint-cli2:0.4.0 README.md
