name: Smoke test packages and container images

on:
  pull_request:
  push:
  schedule:
    - cron: '30 12 * * *'
  workflow_dispatch:

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
      - name: Install Dependencies (npm)
        run: cd markdownlint && npm install --no-package-lock --production
      - name: Run Tests
        run: cd markdownlint && npm run test
      - name: Clean Repository
        run: git clean -dfx
      - name: Use pnpm latest
        uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Install Dependencies (pnpm)
        run: cd markdownlint && pnpm install
      - name: Run Tests
        run: cd markdownlint && npm run test
  markdownlint-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
      - name: Install Dependencies (npm)
        run: cd markdownlint-cli && npm install --no-package-lock --production
      - name: Run Tests
        run: cd markdownlint-cli && npm run test
      - name: Clean Repository
        run: git clean -dfx
      - name: Use pnpm latest
        uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Install Dependencies (pnpm)
        run: cd markdownlint-cli && pnpm install
      - name: Run Tests
        run: cd markdownlint-cli && npm run test
  markdownlint-cli-global:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
      - name: Install Dependencies
        run: sudo npm install --global --no-package-lock --production markdownlint-cli
      - name: Run Tests
        run: cd markdownlint-cli && npm run test
  markdownlint-cli2:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
      - name: Install Dependencies (npm)
        run: cd markdownlint-cli2 && npm install --no-package-lock --production
      - name: Run Tests
        run: cd markdownlint-cli2 && npm run test
      - name: Clean Repository
        run: git clean -dfx
      - name: Use pnpm latest
        uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Install Dependencies (pnpm)
        run: cd markdownlint-cli2 && pnpm install
      - name: Run Tests
        run: cd markdownlint-cli2 && npm run test
  markdownlint-cli2-global:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
      - name: Install Dependencies
        run: sudo npm install --global --no-package-lock --production markdownlint-cli2 markdownlint-cli2-formatter-json markdownlint-cli2-formatter-junit markdownlint-cli2-formatter-pretty markdownlint-cli2-formatter-summarize
      - name: Run Tests
        run: cd markdownlint-cli2 && npm run test
  markdownlint-cli-container:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/igorshubovych/markdownlint-cli:latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Lint
        run: markdownlint README.md
      - name: Lint and fix
        run: markdownlint --fix README.md
  markdownlint-cli-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Lint via Docker
        run: docker run -v $PWD:/workdir ghcr.io/igorshubovych/markdownlint-cli:latest README.md
      - name: Lint and fix via Docker
        run: docker run -v $PWD:/workdir ghcr.io/igorshubovych/markdownlint-cli:latest --fix README.md
  markdownlint-cli2-container-latest:
    runs-on: ubuntu-latest
    container:
      image: davidanson/markdownlint-cli2:latest
      options: -u root
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Lint
        run: markdownlint-cli2 README.md
      - name: Lint and fix
        run: markdownlint-cli2 --fix README.md
      - name: Lint with config
        run: markdownlint-cli2 --config configuration/.markdownlint-cli2.jsonc README.md
  markdownlint-cli2-container-next:
    runs-on: ubuntu-latest
    container:
      image: davidanson/markdownlint-cli2:next
      options: -u root
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Lint
        run: markdownlint-cli2 README.md
      - name: Lint and fix
        run: markdownlint-cli2 --fix README.md
      - name: Lint with config
        run: markdownlint-cli2 --config configuration/.markdownlint-cli2.jsonc README.md
      - name: Lint using output formatters
        run: cd markdownlint-cli2 && markdownlint-cli2 ../README.md
  markdownlint-cli2-docker-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Lint via Docker
        run: docker run -v $PWD:/workdir davidanson/markdownlint-cli2:latest README.md
      - name: Lint and fix via Docker
        run: docker run -v $PWD:/workdir davidanson/markdownlint-cli2:latest --fix README.md
      - name: Lint with config via Docker
        run: docker run -v $PWD:/workdir davidanson/markdownlint-cli2:latest --config configuration/.markdownlint-cli2.jsonc README.md
      - name: Lint via Docker (-rules image)
        run: docker run -v $PWD:/workdir davidanson/markdownlint-cli2-rules:latest README.md
      - name: Lint and fix via Docker (-rules image)
        run: docker run -v $PWD:/workdir davidanson/markdownlint-cli2-rules:latest --fix README.md
      - name: Lint with config via Docker (-rules image)
        run: docker run -v $PWD:/workdir davidanson/markdownlint-cli2-rules:latest --config configuration/.markdownlint-cli2.jsonc README.md
  markdownlint-cli2-docker-next:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Lint via Docker
        run: docker run -v $PWD:/workdir davidanson/markdownlint-cli2:next README.md
      - name: Lint and fix via Docker
        run: docker run -v $PWD:/workdir davidanson/markdownlint-cli2:next --fix README.md
      - name: Lint with config via Docker
        run: docker run -v $PWD:/workdir davidanson/markdownlint-cli2:next --config configuration/.markdownlint-cli2.jsonc README.md
      - name: Lint via Docker (-rules image)
        run: docker run -v $PWD:/workdir davidanson/markdownlint-cli2-rules:next README.md
      - name: Lint and fix via Docker (-rules image)
        run: docker run -v $PWD:/workdir davidanson/markdownlint-cli2-rules:next --fix README.md
      - name: Lint with config via Docker (-rules image)
        run: docker run -v $PWD:/workdir davidanson/markdownlint-cli2-rules:next --config configuration/.markdownlint-cli2.jsonc README.md
